check-leaks: true
color: true
extension:
  - 'js'
file:
  - './test/mixins/ConfigurableMixin-test.js'
  - './test/mixins/MemoryConfigurationMixin-test.js'
  - './test/proxy/Configuration-test.js'
full-trace: true
growl: true
recursive: false
reporter: 'spec'
require: '@babel/register'
# spec: 'test/**/**/*-test.js'
watch: true
